/*
 * FotoWare API
 * This reference documents the available endpoints for FotoWare's API. <br/> Click the Authorize button at the top of the page to try the API with your own FotoWare as a Service tenant.<br/> To enable authorization and testing of the API on an on-premises server, <a target=\"_blank\" href='https://learn.fotoware.com/Integrations_and_APIs/001_The_FotoWare_API/FotoWare_API_Overview/Exploring_the_FotoWare_API_with_Swagger'>please follow the instructions in our software documentation</a><br/> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cominvent.fotoware.model;

import com.cominvent.fotoware.model.ExternalId;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Account
 */
public class AccountTest {
    private final Account model = new Account();

    /**
     * Model tests for Account
     */
    @Test
    public void testAccount() {
        // TODO: test Account
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'hasPassword'
     */
    @Test
    public void hasPasswordTest() {
        // TODO: test hasPassword
    }

    /**
     * Test the property 'deletePassword'
     */
    @Test
    public void deletePasswordTest() {
        // TODO: test deletePassword
    }

    /**
     * Test the property 'forcePasswordChange'
     */
    @Test
    public void forcePasswordChangeTest() {
        // TODO: test forcePasswordChange
    }

    /**
     * Test the property 'allowPasswordChange'
     */
    @Test
    public void allowPasswordChangeTest() {
        // TODO: test allowPasswordChange
    }

    /**
     * Test the property 'lastLoginDate'
     */
    @Test
    public void lastLoginDateTest() {
        // TODO: test lastLoginDate
    }

    /**
     * Test the property 'expires'
     */
    @Test
    public void expiresTest() {
        // TODO: test expires
    }

    /**
     * Test the property 'isEnabled'
     */
    @Test
    public void isEnabledTest() {
        // TODO: test isEnabled
    }

    /**
     * Test the property 'externalIds'
     */
    @Test
    public void externalIdsTest() {
        // TODO: test externalIds
    }

    /**
     * Test the property 'isSsoUser'
     */
    @Test
    public void isSsoUserTest() {
        // TODO: test isSsoUser
    }

}
