/*
 * FotoWare API
 * This reference documents the available endpoints for FotoWare's API. <br/> Click the Authorize button at the top of the page to try the API with your own FotoWare as a Service tenant.<br/> To enable authorization and testing of the API on an on-premises server, <a target=\"_blank\" href='https://learn.fotoware.com/Integrations_and_APIs/001_The_FotoWare_API/FotoWare_API_Overview/Exploring_the_FotoWare_API_with_Swagger'>please follow the instructions in our software documentation</a><br/> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cominvent.fotoware.model;

import com.cominvent.fotoware.model.APIDescriptorServices;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for APIDescriptor
 */
public class APIDescriptorTest {
    private final APIDescriptor model = new APIDescriptor();

    /**
     * Model tests for APIDescriptor
     */
    @Test
    public void testAPIDescriptor() {
        // TODO: test APIDescriptor
    }

    /**
     * Test the property 'server'
     */
    @Test
    public void serverTest() {
        // TODO: test server
    }

    /**
     * Test the property 'screens'
     */
    @Test
    public void screensTest() {
        // TODO: test screens
    }

    /**
     * Test the property 'utcOffset'
     */
    @Test
    public void utcOffsetTest() {
        // TODO: test utcOffset
    }

    /**
     * Test the property 'archives'
     */
    @Test
    public void archivesTest() {
        // TODO: test archives
    }

    /**
     * Test the property 'albums'
     */
    @Test
    public void albumsTest() {
        // TODO: test albums
    }

    /**
     * Test the property 'taxonomies'
     */
    @Test
    public void taxonomiesTest() {
        // TODO: test taxonomies
    }

    /**
     * Test the property 'services'
     */
    @Test
    public void servicesTest() {
        // TODO: test services
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'backgroundTasks'
     */
    @Test
    public void backgroundTasksTest() {
        // TODO: test backgroundTasks
    }

    /**
     * Test the property 'searchURL'
     */
    @Test
    public void searchURLTest() {
        // TODO: test searchURL
    }

}
