/*
 * FotoWare API
 * This reference documents the available endpoints for FotoWare's API. <br/> Click the Authorize button at the top of the page to try the API with your own FotoWare as a Service tenant.<br/> To enable authorization and testing of the API on an on-premises server, <a target=\"_blank\" href='https://learn.fotoware.com/Integrations_and_APIs/001_The_FotoWare_API/FotoWare_API_Overview/Exploring_the_FotoWare_API_with_Swagger'>please follow the instructions in our software documentation</a><br/> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cominvent.fotoware.model;

import com.cominvent.fotoware.model.AssetAncestorsInner;
import com.cominvent.fotoware.model.AssetAttributes;
import com.cominvent.fotoware.model.AssetBuiltinFieldsInner;
import com.cominvent.fotoware.model.AssetCapabilities;
import com.cominvent.fotoware.model.AssetMetadataEditor;
import com.cominvent.fotoware.model.AssetPreviewsInner;
import com.cominvent.fotoware.model.AssetProps;
import com.cominvent.fotoware.model.AssetQuickRenditionsInner;
import com.cominvent.fotoware.model.AssetRenditionsInner;
import com.cominvent.fotoware.model.AssetThumbnailFields;
import com.cominvent.fotoware.model.ConsentStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Asset
 */
public class AssetTest {
    private final Asset model = new Asset();

    /**
     * Model tests for Asset
     */
    @Test
    public void testAsset() {
        // TODO: test Asset
    }

    /**
     * Test the property 'archiveHREF'
     */
    @Test
    public void archiveHREFTest() {
        // TODO: test archiveHREF
    }

    /**
     * Test the property 'ancestors'
     */
    @Test
    public void ancestorsTest() {
        // TODO: test ancestors
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'builtinFields'
     */
    @Test
    public void builtinFieldsTest() {
        // TODO: test builtinFields
    }

    /**
     * Test the property 'capabilities'
     */
    @Test
    public void capabilitiesTest() {
        // TODO: test capabilities
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'doctype'
     */
    @Test
    public void doctypeTest() {
        // TODO: test doctype
    }

    /**
     * Test the property 'downloadcount'
     */
    @Test
    public void downloadcountTest() {
        // TODO: test downloadcount
    }

    /**
     * Test the property 'dropHREF'
     */
    @Test
    public void dropHREFTest() {
        // TODO: test dropHREF
    }

    /**
     * Test the property 'filesize'
     */
    @Test
    public void filesizeTest() {
        // TODO: test filesize
    }

    /**
     * Test the property 'filename'
     */
    @Test
    public void filenameTest() {
        // TODO: test filename
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'linkstance'
     */
    @Test
    public void linkstanceTest() {
        // TODO: test linkstance
    }

    /**
     * Test the property 'consentStatus'
     */
    @Test
    public void consentStatusTest() {
        // TODO: test consentStatus
    }

    /**
     * Test the property 'physicalFileId'
     */
    @Test
    public void physicalFileIdTest() {
        // TODO: test physicalFileId
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'metadataeditcount'
     */
    @Test
    public void metadataeditcountTest() {
        // TODO: test metadataeditcount
    }

    /**
     * Test the property 'metadataEditor'
     */
    @Test
    public void metadataEditorTest() {
        // TODO: test metadataEditor
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    public void modifiedByTest() {
        // TODO: test modifiedBy
    }

    /**
     * Test the property 'permissions'
     */
    @Test
    public void permissionsTest() {
        // TODO: test permissions
    }

    /**
     * Test the property 'pincount'
     */
    @Test
    public void pincountTest() {
        // TODO: test pincount
    }

    /**
     * Test the property 'previewcount'
     */
    @Test
    public void previewcountTest() {
        // TODO: test previewcount
    }

    /**
     * Test the property 'previews'
     */
    @Test
    public void previewsTest() {
        // TODO: test previews
    }

    /**
     * Test the property 'previewToken'
     */
    @Test
    public void previewTokenTest() {
        // TODO: test previewToken
    }

    /**
     * Test the property 'props'
     */
    @Test
    public void propsTest() {
        // TODO: test props
    }

    /**
     * Test the property 'quickRenditions'
     */
    @Test
    public void quickRenditionsTest() {
        // TODO: test quickRenditions
    }

    /**
     * Test the property 'renditions'
     */
    @Test
    public void renditionsTest() {
        // TODO: test renditions
    }

    /**
     * Test the property 'revisioncount'
     */
    @Test
    public void revisioncountTest() {
        // TODO: test revisioncount
    }

    /**
     * Test the property 'thumbnailFields'
     */
    @Test
    public void thumbnailFieldsTest() {
        // TODO: test thumbnailFields
    }

    /**
     * Test the property 'uniqueid'
     */
    @Test
    public void uniqueidTest() {
        // TODO: test uniqueid
    }

    /**
     * Test the property 'workflowcount'
     */
    @Test
    public void workflowcountTest() {
        // TODO: test workflowcount
    }

}
