/*
 * FotoWare API
 * This reference documents the available endpoints for FotoWare's API. <br/> Click the Authorize button at the top of the page to try the API with your own FotoWare as a Service tenant.<br/> To enable authorization and testing of the API on an on-premises server, <a target=\"_blank\" href='https://learn.fotoware.com/Integrations_and_APIs/001_The_FotoWare_API/FotoWare_API_Overview/Exploring_the_FotoWare_API_with_Swagger'>please follow the instructions in our software documentation</a><br/> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cominvent.fotoware.model;

import com.cominvent.fotoware.model.AssetConsentCategoryApiModel;
import com.cominvent.fotoware.model.AssetConsentFlag;
import com.cominvent.fotoware.model.ConsentFormAssetConsentState;
import com.cominvent.fotoware.model.ConsentFormStateCount;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ConsentStatus
 */
public class ConsentStatusTest {
    private final ConsentStatus model = new ConsentStatus();

    /**
     * Model tests for ConsentStatus
     */
    @Test
    public void testConsentStatus() {
        // TODO: test ConsentStatus
    }

    /**
     * Test the property 'assetConsentState'
     */
    @Test
    public void assetConsentStateTest() {
        // TODO: test assetConsentState
    }

    /**
     * Test the property 'approvedConsents'
     */
    @Test
    public void approvedConsentsTest() {
        // TODO: test approvedConsents
    }

    /**
     * Test the property 'declinedConsents'
     */
    @Test
    public void declinedConsentsTest() {
        // TODO: test declinedConsents
    }

    /**
     * Test the property 'consentFlags'
     */
    @Test
    public void consentFlagsTest() {
        // TODO: test consentFlags
    }

    /**
     * Test the property 'consentFormCount'
     */
    @Test
    public void consentFormCountTest() {
        // TODO: test consentFormCount
    }

    /**
     * Test the property 'countByConsentFormState'
     */
    @Test
    public void countByConsentFormStateTest() {
        // TODO: test countByConsentFormState
    }

}
