/*
 * FotoWare API
 * This reference documents the available endpoints for FotoWare's API. <br/> Click the Authorize button at the top of the page to try the API with your own FotoWare as a Service tenant.<br/> To enable authorization and testing of the API on an on-premises server, <a target=\"_blank\" href='https://learn.fotoware.com/Integrations_and_APIs/001_The_FotoWare_API/FotoWare_API_Overview/Exploring_the_FotoWare_API_with_Swagger'>please follow the instructions in our software documentation</a><br/> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cominvent.fotoware.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for FullAPIDescriptorUserManagement
 */
public class FullAPIDescriptorUserManagementTest {
    private final FullAPIDescriptorUserManagement model = new FullAPIDescriptorUserManagement();

    /**
     * Model tests for FullAPIDescriptorUserManagement
     */
    @Test
    public void testFullAPIDescriptorUserManagement() {
        // TODO: test FullAPIDescriptorUserManagement
    }

    /**
     * Test the property 'userList'
     */
    @Test
    public void userListTest() {
        // TODO: test userList
    }

    /**
     * Test the property 'groupList'
     */
    @Test
    public void groupListTest() {
        // TODO: test groupList
    }

    /**
     * Test the property 'guestUser'
     */
    @Test
    public void guestUserTest() {
        // TODO: test guestUser
    }

    /**
     * Test the property 'adminUser'
     */
    @Test
    public void adminUserTest() {
        // TODO: test adminUser
    }

    /**
     * Test the property 'everyoneGroup'
     */
    @Test
    public void everyoneGroupTest() {
        // TODO: test everyoneGroup
    }

    /**
     * Test the property 'registeredUsersGroup'
     */
    @Test
    public void registeredUsersGroupTest() {
        // TODO: test registeredUsersGroup
    }

    /**
     * Test the property 'siteOwner'
     */
    @Test
    public void siteOwnerTest() {
        // TODO: test siteOwner
    }

}
