/*
 * FotoWare API
 * This reference documents the available endpoints for FotoWare's API. <br/> Click the Authorize button at the top of the page to try the API with your own FotoWare as a Service tenant.<br/> To enable authorization and testing of the API on an on-premises server, <a target=\"_blank\" href='https://learn.fotoware.com/Integrations_and_APIs/001_The_FotoWare_API/FotoWare_API_Overview/Exploring_the_FotoWare_API_with_Swagger'>please follow the instructions in our software documentation</a><br/> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cominvent.fotoware.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for FullAPIDescriptorWidgetsFwdtServices
 */
public class FullAPIDescriptorWidgetsFwdtServicesTest {
    private final FullAPIDescriptorWidgetsFwdtServices model = new FullAPIDescriptorWidgetsFwdtServices();

    /**
     * Model tests for FullAPIDescriptorWidgetsFwdtServices
     */
    @Test
    public void testFullAPIDescriptorWidgetsFwdtServices() {
        // TODO: test FullAPIDescriptorWidgetsFwdtServices
    }

    /**
     * Test the property 'open'
     */
    @Test
    public void openTest() {
        // TODO: test open
    }

    /**
     * Test the property 'edit'
     */
    @Test
    public void editTest() {
        // TODO: test edit
    }

    /**
     * Test the property 'crop'
     */
    @Test
    public void cropTest() {
        // TODO: test crop
    }

}
