/*
 * FotoWare API
 * This reference documents the available endpoints for FotoWare's API. <br/> Click the Authorize button at the top of the page to try the API with your own FotoWare as a Service tenant.<br/> To enable authorization and testing of the API on an on-premises server, <a target=\"_blank\" href='https://learn.fotoware.com/Integrations_and_APIs/001_The_FotoWare_API/FotoWare_API_Overview/Exploring_the_FotoWare_API_with_Swagger'>please follow the instructions in our software documentation</a><br/> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cominvent.fotoware.model;

import com.cominvent.fotoware.model.FullAPIDescriptorOrderAdminViews;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for FullAPIDescriptorOrderAdmin
 */
public class FullAPIDescriptorOrderAdminTest {
    private final FullAPIDescriptorOrderAdmin model = new FullAPIDescriptorOrderAdmin();

    /**
     * Model tests for FullAPIDescriptorOrderAdmin
     */
    @Test
    public void testFullAPIDescriptorOrderAdmin() {
        // TODO: test FullAPIDescriptorOrderAdmin
    }

    /**
     * Test the property 'history'
     */
    @Test
    public void historyTest() {
        // TODO: test history
    }

    /**
     * Test the property 'pending'
     */
    @Test
    public void pendingTest() {
        // TODO: test pending
    }

    /**
     * Test the property 'approved'
     */
    @Test
    public void approvedTest() {
        // TODO: test approved
    }

    /**
     * Test the property 'rejected'
     */
    @Test
    public void rejectedTest() {
        // TODO: test rejected
    }

    /**
     * Test the property 'views'
     */
    @Test
    public void viewsTest() {
        // TODO: test views
    }

}
