/*
 * FotoWare API
 * This reference documents the available endpoints for FotoWare's API. <br/> Click the Authorize button at the top of the page to try the API with your own FotoWare as a Service tenant.<br/> To enable authorization and testing of the API on an on-premises server, <a target=\"_blank\" href='https://learn.fotoware.com/Integrations_and_APIs/001_The_FotoWare_API/FotoWare_API_Overview/Exploring_the_FotoWare_API_with_Swagger'>please follow the instructions in our software documentation</a><br/> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cominvent.fotoware.model;

import com.cominvent.fotoware.model.MetadataViewBuiltinFieldsDescription;
import com.cominvent.fotoware.model.MetadataViewBuiltinFieldsNotes;
import com.cominvent.fotoware.model.MetadataViewBuiltinFieldsRating;
import com.cominvent.fotoware.model.MetadataViewBuiltinFieldsStatus;
import com.cominvent.fotoware.model.MetadataViewBuiltinFieldsTags;
import com.cominvent.fotoware.model.MetadataViewBuiltinFieldsTitle;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for MetadataViewBuiltinFields
 */
public class MetadataViewBuiltinFieldsTest {
    private final MetadataViewBuiltinFields model = new MetadataViewBuiltinFields();

    /**
     * Model tests for MetadataViewBuiltinFields
     */
    @Test
    public void testMetadataViewBuiltinFields() {
        // TODO: test MetadataViewBuiltinFields
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
