/*
 * FotoWare API
 * This reference documents the available endpoints for FotoWare's API. <br/> Click the Authorize button at the top of the page to try the API with your own FotoWare as a Service tenant.<br/> To enable authorization and testing of the API on an on-premises server, <a target=\"_blank\" href='https://learn.fotoware.com/Integrations_and_APIs/001_The_FotoWare_API/FotoWare_API_Overview/Exploring_the_FotoWare_API_with_Swagger'>please follow the instructions in our software documentation</a><br/> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cominvent.fotoware.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Information about the successful upload
 */
@JsonPropertyOrder({
  BatchUploadStatusResult.JSON_PROPERTY_ASSET_URL,
  BatchUploadStatusResult.JSON_PROPERTY_ASSET_DETAILS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-20T14:14:21.267957+01:00[Europe/Oslo]")
public class BatchUploadStatusResult {
  public static final String JSON_PROPERTY_ASSET_URL = "assetUrl";
  private String assetUrl;

  public static final String JSON_PROPERTY_ASSET_DETAILS = "assetDetails";
  private String assetDetails;

  public BatchUploadStatusResult() { 
  }

  public BatchUploadStatusResult assetUrl(String assetUrl) {
    this.assetUrl = assetUrl;
    return this;
  }

   /**
   * The API URL of the uploaded asset
   * @return assetUrl
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASSET_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAssetUrl() {
    return assetUrl;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssetUrl(String assetUrl) {
    this.assetUrl = assetUrl;
  }


  public BatchUploadStatusResult assetDetails(String assetDetails) {
    this.assetDetails = assetDetails;
    return this;
  }

   /**
   * The asset representation of the asset
   * @return assetDetails
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASSET_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAssetDetails() {
    return assetDetails;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssetDetails(String assetDetails) {
    this.assetDetails = assetDetails;
  }


  /**
   * Return true if this BatchUploadStatusResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchUploadStatusResult batchUploadStatusResult = (BatchUploadStatusResult) o;
    return Objects.equals(this.assetUrl, batchUploadStatusResult.assetUrl) &&
        Objects.equals(this.assetDetails, batchUploadStatusResult.assetDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetUrl, assetDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchUploadStatusResult {\n");
    sb.append("    assetUrl: ").append(toIndentedString(assetUrl)).append("\n");
    sb.append("    assetDetails: ").append(toIndentedString(assetDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `assetUrl` to the URL query string
    if (getAssetUrl() != null) {
      joiner.add(String.format("%sassetUrl%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAssetUrl()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `assetDetails` to the URL query string
    if (getAssetDetails() != null) {
      joiner.add(String.format("%sassetDetails%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAssetDetails()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

