/*
 * FotoWare API
 * This reference documents the available endpoints for FotoWare's API. <br/> Click the Authorize button at the top of the page to try the API with your own FotoWare as a Service tenant.<br/> To enable authorization and testing of the API on an on-premises server, <a target=\"_blank\" href='https://learn.fotoware.com/Integrations_and_APIs/001_The_FotoWare_API/FotoWare_API_Overview/Exploring_the_FotoWare_API_with_Swagger'>please follow the instructions in our software documentation</a><br/> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cominvent.fotoware.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.cominvent.fotoware.model.SharingLinkListAddedSharesInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SharingLinkList
 */
@JsonPropertyOrder({
  SharingLinkList.JSON_PROPERTY_ADDED_SHARES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SharingLinkList {
  public static final String JSON_PROPERTY_ADDED_SHARES = "addedShares";
  private List<SharingLinkListAddedSharesInner> addedShares;

  public SharingLinkList() { 
  }

  public SharingLinkList addedShares(List<SharingLinkListAddedSharesInner> addedShares) {
    this.addedShares = addedShares;
    return this;
  }

  public SharingLinkList addAddedSharesItem(SharingLinkListAddedSharesInner addedSharesItem) {
    if (this.addedShares == null) {
      this.addedShares = new ArrayList<>();
    }
    this.addedShares.add(addedSharesItem);
    return this;
  }

   /**
   * Get addedShares
   * @return addedShares
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDED_SHARES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SharingLinkListAddedSharesInner> getAddedShares() {
    return addedShares;
  }


  @JsonProperty(JSON_PROPERTY_ADDED_SHARES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddedShares(List<SharingLinkListAddedSharesInner> addedShares) {
    this.addedShares = addedShares;
  }


  /**
   * Return true if this SharingLinkList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SharingLinkList sharingLinkList = (SharingLinkList) o;
    return Objects.equals(this.addedShares, sharingLinkList.addedShares);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addedShares);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SharingLinkList {\n");
    sb.append("    addedShares: ").append(toIndentedString(addedShares)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `addedShares` to the URL query string
    if (getAddedShares() != null) {
      for (int i = 0; i < getAddedShares().size(); i++) {
        if (getAddedShares().get(i) != null) {
          joiner.add(getAddedShares().get(i).toUrlQueryString(String.format("%saddedShares%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

