/*
 * FotoWare API
 * This reference documents the available endpoints for FotoWare's API. <br/> Click the Authorize button at the top of the page to try the API with your own FotoWare as a Service tenant.<br/> To enable authorization and testing of the API on an on-premises server, <a target=\"_blank\" href='https://learn.fotoware.com/Integrations_and_APIs/001_The_FotoWare_API/FotoWare_API_Overview/Exploring_the_FotoWare_API_with_Swagger'>please follow the instructions in our software documentation</a><br/> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cominvent.fotoware.api;

import com.cominvent.fotoware.client.ApiException;
import com.cominvent.fotoware.model.RenditionRequest;
import com.cominvent.fotoware.model.RenditionResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for RenditionsApi
 */
@Ignore
public class RenditionsApiTest {

    private final RenditionsApi api = new RenditionsApi();

    
    /**
     * Get the rendition download url
     *
     * The representation of an asset gives you a list with predefined renditions available for the asset. This request uses the url to one of those renditions to generate a download url for the asset rendition. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fotowebServicesRenditionsPostTest() throws ApiException {
        RenditionRequest renditionRequest = null;
        RenditionResponse response = 
        api.fotowebServicesRenditionsPost(renditionRequest);
        
        // TODO: test validations
    }
    
}
